services:
  - type: web
    name: backend-todo
    env: node
    region: oregon
    plan: free
    buildCommand: "echo 'Build skipped (handled by GitHub Actions)'"
    startCommand: "node dist/server.js"
    branch: main
    autoDeploy: false # los deploy solo vienen desde GitHub
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
