name: Build and Deploy Docker to Render

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Instalar firebase admin
      - name: Install firebase tools
        run: npm install -g firebase-tools

      # Conectandose a firebase
      - name: Authenticate to Firebase
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/firebaseServiceAccount.json
          firebase login:ci --token "$(jq -r '.token' $HOME/firebaseServiceAccount.json)" || true
          firebase use --add ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      # Hacer build
      - name: Build backend
        run: npm run ci && npm run build

      # Deploy en firebase
      - name: Deploy Functions
        run: firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
